version: "3.7"

services:
  api:
    image: node:lts
    command: "bash -c 'npm i && npm run dev'"
    volumes:
      - .:/usr/src/app:z
    working_dir: /usr/src/app
    network_mode: 'host'
    env_file: .env
    depends_on:
      - db

  db:
    image: mariadb:lts
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

volumes:
  data: