version: "3.7"

services:
  api:
    image: node:lts
    command: "bash -c 'npm i && npm run dev'"
    volumes:
      - .:/usr/src/app:z
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db

  db:
    image: mariadb:lts
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  data: